### ISSUE TITLE
cannot close the pool in process on exit

### ISSUE THREAD

**Issue by hairinwind** [MonetDB/monetdb-pool-nodejs#1]
Here is the pseudocode

var pool = new MonetDBPool(poolOptions, dbOptions);
pool.connect();

//... run queries...

process.on('exit', () => {
    console.log('process on exit...');
    pool.close();
}); 

the process on exit was never triggered.

**Comment by rcijvat** [comment]
Could you also post the poolOptions you provided?

**Comment by hairinwind** [comment]
var poolOptions = {
    nrConnections: 8
};

It could be an issue of the monetdb package, https://www.npmjs.com/package/monetdb. 
I use the monetdb package to get the connection, then do some queries. Then I try to close the connection in the "process on exit". Same, the close method was never triggered. 

Thanks,

**Comment by rcijvat** [comment]
You should put the call to pool.close() outside of the process exit handler. The pool will keep the process running, until pool.close is called. pool.close is only called when the process exits. Hence the process will never exit. Please let me know if you have more issues.

**Comment by hairinwind** [comment]
My understanding is that the pool should allow me to initialize it when the app is started and close it before the app exits.  

People use pool to reuse the connection which saves the time to create the database connection. For example, a web app accepts user request and then get connection to the database to read/write the data. If the pool has to be closed after this request, then all connections are gone. When the next request comes in, the app need to create the connection to the db again. Does it make sense?

**Comment by rcijvat** [comment]
This is not how this pool is intended. You can use it exactly like a normal MonetDB connection, only under the hood multiple connections are kept open for you. That means that you also have to call connect on it before queries are being handled, and close it explicitly before you can expect your application to exit.
